const SQL_ERROR_CODES = {
  NO_RESULT: 0,
  CONNEXION_REFUSED: 'ECONNREFUSED',
  DEFAULT: 'Unknown error'
};

const SERVER_ERROR_CODES = {
  PORT_ALREADY_IN_USE: 'EADDRINUSE'
};

const HTTP_ERROR_CODES = {
  TOKEN_EXPIRED: 4012,
  UNAUTHORIZED: 4013,
};

const TOKEN_ERROR_CODES = {
  EXPIRED: 'TokenExpiredError'
};

module.exports = {
  SQL_ERROR_CODES: SQL_ERROR_CODES,
  SERVER_ERROR_CODES: SERVER_ERROR_CODES,
  TOKEN_ERROR_CODES: TOKEN_ERROR_CODES,
  HTTP_ERROR_CODES: HTTP_ERROR_CODES
};
